### ISSUE TITLE
Can't run tests in Docker Containers

### ISSUE THREAD

**Issue by matthewtusker** [open-telemetry/opentelemetry-ruby-contrib#1097]
I'm trying to follow [the instructions in the PG Instrumentation specs](https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/39056a3190561e87bfa4c5103508cffb0e133713/instrumentation/pg/test/opentelemetry/instrumentation/pg/instrumentation_test.rb#L14-L21) to run the tests, but the tests fail to load `pg` properly:

```
❯ docker-compose run ex-instrumentation-pg-test bundle exec rake test
[+] Creating 1/0
 ✔ Container opentelemetry-ruby-contrib-postgres-1  Running                                                                                         0.0s
/bundle/ruby/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/core_ext/object/blank.rb:121: warning: method redefined; discarding old blank?
/bundle/ruby/3.2.0/gems/rubocop-1.64.1/lib/rubocop/core_ext/string.rb:19: warning: previous definition of blank? was here
<internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require': cannot load such file -- pg (LoadError)
        from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from /app/instrumentation/pg/test/opentelemetry/instrumentation/pg/instrumentation_test.rb:9:in `<top (required)>'
        from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from /bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/rake_test_loader.rb:21:in `block in <main>'
        from /bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/rake_test_loader.rb:6:in `select'
        from /bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/rake_test_loader.rb:6:in `<main>'
rake aborted!
Command failed with status (1)
/bundle/ruby/3.2.0/gems/rake-13.2.1/exe/rake:27:in `<top (required)>'
/bundle/bin/bundle:108:in `load'
/bundle/bin/bundle:108:in `<main>'
Tasks: TOP => test
(See full trace by running task with --trace)
```

I can see Appraisal in the files for the `pg` instrumentation Gem, but that doesn't seem to be able to install the pg due to some C error (I'm struggling to see it through the screed of warnings that are also displayed.

Am I running the tests wrong? I'm trying to create a new Instrumentation Gem and I'm using PG/Mysql2 as prior art to figure out how to build it, but at the moment I don't see how I'm supposed to be running tests, or at the very least the instructions that are there seem to be either incomplete or incorrect.

**Comment by xuan-cao-swi** [comment]
`bundle exec rake test` only works if Gemfile contains `gem 'pg'` (as bundler only works with Gemfile).

In current pg [Gemfile](https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/main/instrumentation/pg/Gemfile) there is no `pg`; so if you want to keep doing `bundle exec rake test`, then you need to add this gem.

Appraisal is the ideal way. The C build issue you have with pg 1.2.3 could cause by many factors. pg 1.2.3 is quite old and it may not work with your machine (esp if you are using arm based containers). I suggest to remove that [appraise](https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/main/instrumentation/pg/Appraisals#L4-L6) for your testing

**Comment by matthewtusker** [comment]
Thanks for the explanation. How are these tests being run in CI? I would assume that any issue I'm having would be present in CI also if it's being run regularly.

Removing `pg-1.2` from `Appraisals` appears to have fixed the issue and let me run the tests. Should I raise this as a PR to fix it for others?

**Comment by matthewtusker** [comment]
So, I've just looked at a recent CI run and it's failing, but not reporting back as failed: https://github.com/open-telemetry/opentelemetry-ruby-contrib/actions/runs/10191261459/job/28192278572#step:4:112

**Comment by xuan-cao-swi** [comment]
Thanks for pointing it out. It's indeed an issue that should be fixed.

**Comment by robbkidd** [comment]
This has unearthed a few issues in the CI suite.

Specific to the `pg` gem, version 1.2.x will not work with Ruby 3.0+. 

* Install fails on compiling pg's extensions under any Ruby 3.x.
* The error is `pg_result.c:1590:65: error: 'rb_cData' undeclared`.
* This error was addressed by pg maintainers in [this commit](https://github.com/ged/ruby-pg/commit/4f1229c72bd9a280b9cfee37dc9b9ee3fec895db).
* The first `pg` release to include that commit was v1.3.0.

So we intend to drop support for pg v1.2.

**Comment by robbkidd** [comment]
@matthewtusker Would you like to open a PR removing the `appraise 'pg-1.2'` block from pg's Appraisals? If not, we'll take care of that in the next day or so.

**Comment by matthewtusker** [comment]
Yeah, I can take a look. Does something also need to be done to ensure that CI fails properly? I feel like this issue should have been identified a lot sooner, and CI would be the place to find it.

**Comment by matthewtusker** [comment]
I've raised a PR but I'm not going to be able to accept the CLA until I've found out what process we need to follow at my work. I may have to leave the PR open for a while, or someone else can recreate the PR and submit it. The changes aren't complex.
