### ISSUE TITLE
Does not appear to be compatible with Redis 5.0

### ISSUE THREAD

**Issue by mockdeep** [open-telemetry/opentelemetry-ruby-contrib#177]
**Description of the bug**

I'm having a hard time tracing exactly why this error is happening when upgrading Redis to 5.0, but it appears to be related to OpenTelemetry:

```
       NoMethodError: undefined method `inherit_socket' for {:peer_service=>nil, :trace_root_spans=>true, :db_statement=>:obfuscate}:Hash
           /home/circleci/app/vendor/bundle/ruby/3.0.0/gems/redis-client-0.11.0/lib/redis_client.rb:602:in `ensure_connected'
           /home/circleci/app/vendor/bundle/ruby/3.0.0/gems/redis-client-0.11.0/lib/redis_client.rb:213:in `call_v'
           /home/circleci/app/vendor/bundle/ruby/3.0.0/gems/redis-5.0.5/lib/redis/client.rb:73:in `call_v'
           /home/circleci/app/vendor/bundle/ruby/3.0.0/gems/redis-5.0.5/lib/redis.rb:167:in `block in send_command'
           /home/circleci/app/vendor/bundle/ruby/3.0.0/gems/redis-5.0.5/lib/redis.rb:166:in `synchronize'
           /home/circleci/app/vendor/bundle/ruby/3.0.0/gems/redis-5.0.5/lib/redis.rb:166:in `send_command'
           /home/circleci/app/vendor/bundle/ruby/3.0.0/gems/redis-5.0.5/lib/redis/commands/pubsub.rb:8:in `publish'
           /home/circleci/app/vendor/bundle/ruby/3.0.0/gems/actioncable-7.0.4/lib/action_cable/subscription_adapter/redis.rb:28:in `broadcast'
           /home/circleci/app/vendor/bundle/ruby/3.0.0/gems/actioncable-7.0.4/lib/action_cable/subscription_adapter/channel_prefix.rb:8:in `broadcast'
           /home/circleci/app/vendor/bundle/ruby/3.0.0/gems/actioncable-7.0.4/lib/action_cable/server/broadcasting.rb:48:in `block in broadcast'
           /home/circleci/app/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.4/lib/active_support/notifications.rb:208:in `instrument'
           /home/circleci/app/vendor/bundle/ruby/3.0.0/gems/actioncable-7.0.4/lib/action_cable/server/broadcasting.rb:46:in `broadcast'
           /home/circleci/app/vendor/bundle/ruby/3.0.0/gems/actioncable-7.0.4/lib/action_cable/server/broadcasting.rb:25:in `broadcast'
           /home/circleci/app/vendor/bundle/ruby/3.0.0/gems/actioncable-7.0.4/lib/action_cable/channel/broadcasting.rb:15:in `broadcast_to'
```

**Share details about your runtime**

Operating system details: Linux, Ubuntu 20.04 LTS
RUBY_ENGINE: "ruby"
RUBY_VERSION: "3.0.4"
RUBY_DESCRIPTION: "ruby 3.0.4p208 (2022-04-12 revision 3fa771dded) [x86_64-linux]"
We're using Sidekiq Enterprise and ActiveJob. This issue shows up if we use Sidekiq 6.x or 7.x.

**Share a simplified reproduction if possible**

Sorry, I'm not sure I can put together a simple repro for this.

**Comment by plantfansam** [comment]
Are you on `opentelemetry-instrumentation-redis` version `0.24.0`? There was a fix for 5.0 merged in here: https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/121 that was released in `0.24.0`: https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/124

**Comment by mockdeep** [comment]
@plantfansam that looks like it might do the trick. We're currently relying on the `opentelemetry-instrumentation-all` gem, though, which hasn't been updated for the latest release.

**Comment by ahayworth** [comment]
@mockdeep We (@plantfansam specifically) _just_ pushed a new version of `-all` that includes the updated redis dependency 🎉 - https://rubygems.org/gems/opentelemetry-instrumentation-all/versions/0.28.0

Give it a whirl, let us know if that fixes it? 😄

**Comment by mockdeep** [comment]
Sorry for the delay. It seems to be working now. Thanks!
